RUNNER:
  name: "PPORunner"
ENVS_NAME: ""
NUM_ENVIRONMENTS: 1
NUM_UPDATES: 500
CUDA: True
USE_TORCHSCRIPT: False
TENSORBOARD_DIR: "tb"
ERASE_EXISTING_TB: True
ACTOR_CRITIC:
  name: "ActorCritic"
  net:
    name: "MLPBase"
    hidden_sizes: [256, 128, 64]
    activation: "elu"
  critic:
    name: "MLPCritic"
    hidden_sizes: []
    activation: "elu"
    is_head: True
  action_distribution:
    name: "GaussianActDist"
    min_sigma: 1.0e-6
    max_sigma: 1.0
    sigma_as_params: True
    clip_sigma: False
RL:
  scheduler:
    name: AdaptiveScheduler
#    name: IdentityScheduler
    kl_threshold: 0.008
    min_lr: 1.0e-6
    max_lr: 1.0e-2
  PPO:
    clip_param: 0.2
    ppo_epoch: 1
    num_mini_batch: 4
    value_loss_coef: 2.0
    entropy_coef: 0.000
    lr: 3.0e-4
    eps: 1.0e-5
    max_grad_norm: 1.0
    num_steps: 16
    use_linear_clip_decay: False
    use_clipped_value_loss: False
    use_normalized_advantage: True

  use_gae: True
  gamma: 0.99
  tau: 0.95
  use_linear_lr_decay: False
  reward_window_size: 50
  use_normalized_advantage: True
  reward_scale: 0.01
