TENSORBOARD_DIR: ''
SEED: 1
CUDA: True
RECURRENT_POLICY: False
NUM_ENVIRONMENTS: 100
NUM_UPDATES: 10000
TOTAL_NUM_STEPS: 1000000000
LOG_INTERVAL: 10

RL:
  PPO:
    clip_param: 0.2
    ppo_epoch: 4
    num_mini_batch: 4
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 0.00025
    eps: 0.00001
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50

    use_normalized_advantage: True
    use_double_buffered_sampler: False

    reward_terms: 0

ENVIRONMENT:
  MAX_MOVEMENT: 3
  NUM_KNOBS: 1
  SUCCESS_THRESH: 1.0
  MAX_STEPS: 200